# Site settings
title: MaxCloth.IND
header-img: img/home-bg.jpg
email: info@maxcloth.ga
description: "MaxCloth.IND :: Pimp up your cloth!"
baseurl: ""
url: "http://blog.maxcloth.ga"
twitter_username: maxcloth
github_username:  maxcloth
facebook_username:  maxcloth

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
